version: '3'
services:
    sync_service:
        container_name: sync_service_container
        image: sync-service
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ~/Documents/MTSport/temp_dir:/home/node/app
